modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="oms_forge"
version="1.0.0"
displayName="OMS Forge"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Mr.Gourmet"

[[dependencies.oms_forge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.oms_forge]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0]"
    ordering="NONE"
    side="BOTH"



